import { useEffect, useState } from "react"
import Head from "next/head"
import styles from "@/components/styles/Home.module.css"
import Modal from "../components/Modal"
import { broadcastTx, deriveWallet, getBalance, createTx } from "../lib/wallet-core" 
import { getOrMakeStoreAndGetPrivateKey } from "../lib/storage"
import { hex } from "@scure/base"

export default function Home() {
  // Manage the private keys
  const privateKey = getOrMakeStoreAndGetPrivateKey()
  console.log(`Private key:\n${hex.encode(privateKey)}`)
  const { address } = deriveWallet(privateKey)

  // Manage the state
  const [recipient, setRecipient] = useState("")
  const [amount, setAmount] = useState(0)
  const [balance, setBalance] = useState(0)
  const [tx, setTx] = useState("")
  const [txid, setTxid] = useState("")

  // Fetch and set the balance
  useEffect(() => {
    getBalance(address).then((balance) => {
      setBalance(balance)
    })
  }, [balance])

  // Set the page title
  const title = "BitcoinWallet"

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Modal
        id="sendModal"
        title="Send"
        action={async () => {
          const newTx = await createTx(privateKey, recipient, amount)
          setTx(newTx)
          const txid = await broadcastTx(newTx)
          setTxid(txid)
        }}
        actionLabel="Send"
        body={
          <>
            <div className="mb-3">
              <label htmlFor="recipient" className="form-label">Recipient</label>
              <input className="form-control" id="recipient" value={recipient} onChange={e => setRecipient(e.target.value)} />
            </div>
            <div className="mb-3">
              <label htmlFor="amount" className="form-label">Amount</label>
              <input className="form-control" id="amount" value={amount} onChange={e => setAmount(e.target.value)} />
            </div>
          </>
        }
      />
      <Modal
        id="receiveModal"
        title="Receive"
        body={
          <>
            <p>Address:</p>
            <p>{address}</p>
          </>
        }
      />
      <main className={styles.main}>
        <h1>BitcoinWallet</h1>

        <div>
          <h1 className="display-1">{balance / 10**8}</h1>
          <h2 className="text-center">BTC</h2>
        </div>

        { tx ? (
          <textarea className="form-control" id="tx" rows="5" value={tx} readOnly></textarea>
        ) : null }

        { txid ? (
          <>
            <a className="link-primary" href={`https://mempool.space/tx/${txid}`}
              target="_blank" rel="noopener noreferrer">
              {txid}
            </a>
          </>
        ) : null }

        <div className="d-grid gap-2 col-6 mx-auto">
          <button className="btn btn-primary" type="button"
            data-bs-toggle="modal" data-bs-target="#sendModal">
            Send
          </button>
          <button className="btn btn-secondary" type="button"
            data-bs-toggle="modal" data-bs-target="#receiveModal">
            Receive
          </button>
        </div>

        <div className={styles.grid}>
        </div>
      </main>
    </>
  )
}
