import Head from 'next/head'
import styles from '@/components/styles/Home.module.css'
import SendModal from '../components/SendModal'

import * as btc from '@scure/btc-signer'
import * as secp from '@noble/secp256k1'
import { hex } from '@scure/base'

const send = () => {
  return 0
}

const receive = () => {
  return 0
}

const createWallet = () => {
  const privateKey = secp.utils.randomPrivateKey()
  const publicKey = secp.getPublicKey(privateKey, true)

  const scriptInfo = btc.p2wpkh(publicKey)
  const address = scriptInfo.address

  return { privateKey, publicKey, address }
}

export default function Home() {
  const title = "BitcoinWallet"

  const { privateKey, publicKey, address } = createWallet()

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>BitcoinWallet</h1>

        <div className="d-grid gap-2 col-6 mx-auto">
          <button className="btn btn-primary" type="button"
            data-bs-toggle="modal" data-bs-target="#exampleModal">
            Send
          </button>
          <button className="btn btn-secondary" type="button" onClick={receive}>
            Receive
          </button>
        </div>

        <div className={styles.grid}>
        </div>
      </main>
    </>
  )
}
